import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div>
    <nav className="flex justify-around items-center m-3 text-xl font-semibold italic rounded-md p-3  bg-sky-300">
            <img src="/img/logo.jpg" alt="" className="w-10 h-10 rounded full"/>
            <span className="flex justify-evenly text-pink-500 hover:text-fuchsia-700">NADIA WARDA</span>
            <ul className="flex justify-between items-stretch gap-5 ">
                
                  <li className="text-pink-500 hover:text-fuchsia-700">  <Link href="/">Home</Link></li>
                    <li className="text-pink-500 hover:text-fuchsia-700"><Link href='/about'>About</Link></li>
                    <li className="text-pink-500 hover:text-fuchsia-700"><Link href="/cards">Cards</Link></li>
                    <li className="text-pink-500 hover:text-fuchsia-700"><Link href="/contact">Contact</Link></li>
                    
            </ul>
        </nav>
   </div>
        {children}
      </body>
    </html>
  );
}
